import Head from "next/head";
import Form from "components/Form";
import styles from "./Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Revenue Group Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.left}>
        <Form />
      </div>
      <div className={styles.right}></div>
    </div>
  );
}
